### ISSUE TITLE
Used reserved names

### ISSUE THREAD

**Issue by aka-sps** [r35382/bnflite#1]
INTERNATIONAL STANDARD ISO/IEC14882:2011(E) Third edition 2011-09-01
> 17.6.4.3.2 Global names [global.names]
> 1 Certain sets of names and function signatures are always reserved to the implementation:
>  — Each name that contains a double underscore _ _ or **begins with an underscore followed by an uppercase letter** (2.12) is reserved to the implementation for any use.
> — Each name that begins with an underscore is reserved to the implementation for use as a name in the global namespace.

**Comment by r35382** [comment]
Underscore '_' is used to distinguish _bnflite_ internal statements from _bnflite_ API statements. The issuer treats 'reserved' term as 'forbidden' for everyone that is too narrow.  In fact, it is the rule for applications.
