### ISSUE TITLE
BNF sucks

### ISSUE THREAD

**Issue by hinell** [r35382/bnflite#3]
Consider something better, like:
* [EBNF]
* [Wirth syntax notation]

[EBNF]: https://en.wikipedia.org/wiki/EBNF
[Wirth syntax notation]: https://en.wikipedia.org/wiki/Wirth_syntax_notation

**Comment by r35382** [comment]
1)BNFLite EDSL is extended by EBNF concept (pls be careful before issue posting)
2) wirth syntax notation has no novelty
